input_size = [224, 224]  # (height, width)
crop_size = 224

conf = dict(
    env=dict(
        debug=False,
        CUDA_VISIBLE_DEVICES="3",
        mode="train",
        cuda=True,
        wandb=True,
        saved_model_directory="model_ckpt",
        project_name="facial-token",
        task="classification",
        train_fold=1,
        epoch=10000,
        early_stop_epoch=300,
    ),
    model=dict(
        name="Mobileone_s0_face_emotion_recognition",
        num_class=7,
        input_size=input_size,
        saved_ckpt="pretrained/ImageNet/mobileone_s0_unfused.pth.tar",
    ),
    dataloader_train=dict(
        name="Image2Vector",
        mode="train",
        data_path="/path/to/AffectNet-HQ/train.csv",
        label_cols=["label"],  # for multiple classification
        data_cache=False,
        weighted_sampler=False,
        batch_size=32,
        input_size=input_size,
        workers=16,
        augmentations=dict(
            transform_blur=0.3,
            transform_clahe=0.1,
            transform_cutmix=0.0,
            transform_coarse_dropout=0.5,
            transform_fancyPCA=0.1,
            transform_fog=0.05,
            transform_g_noise=0.3,
            transform_jitter=0.1,
            transform_hflip=0.5,
            transform_vflip=0.0,
            transform_jpeg=0.3,
            transform_mixup=0.5,
            transform_perspective=0.1,
            transform_rand_resize=0.0,
            transform_rand_crop=crop_size,
            transform_resize=input_size,
            transform_rain=0.05,
            transform_rotate=0.3,
        ),
    ),
    dataloader_valid=dict(
        name="Image2Vector",
        mode="valid",
        data_path="/path/to/AffectNet-HQ/valid.csv",
        label_cols=["label"],
        data_cache=False,
        weighted_sampler=False,
        batch_size=32,
        input_size=input_size,
        workers=16,
    ),
    criterion=dict(
        name="LabelSmoothingCrossEntropyLoss", epsilon=1e-8, reduction="mean"
    ),
    optimizer=dict(
        name="AdamW",
        lr=1e-4,
        lr_min=1e-6,
        weight_decay=5e-3,
    ),
    scheduler=dict(name="WarmupCosine", cycles=50, warmup_epoch=20),
)
